version: '3.9'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  products-api:
    image: products-api:latest
    deploy:
      replicas: 3
    expose:
      - 3000
    environment:
      VIRTUAL_HOST: products-api.local
      VIRTUAL_PORT: 3000
      PORT: 3000
  stock-api:
    image: stock-api:latest
    deploy:
      replicas: 2
    expose:
      - 3000
    environment:
      VIRTUAL_HOST: stock-api.local
      VIRTUAL_PORT: 3000
      PORT: 3000
  orders-api:
    image: orders-api:latest
    deploy:
      replicas: 1
    expose:
      - 3000
    environment:
      VIRTUAL_HOST: orders-api.local
      VIRTUAL_PORT: 3000
      PORT: 3000
      PRODUCTS_API: http://products-api:3000/api
      STOCK_API: http://stock-api:3000/api
    depends_on:
      - products-api
      - stock-api

networks:
  default:
    name: ms-arch_network
    driver: bridge