import express from 'express';
import * as jsonServer from 'json-server';
import * as path from 'path';

const host = process.env.HOST ?? 'localhost';
const port = process.env.PORT ? Number(process.env.PORT) : 3000;

const data = {
  products: [
    {
      id: 1,
      name: 'Settlers of Catan',
      category: 'Strategy',
      players: '3-4',
      age_range: '10+',
      playing_time: '60 minutes',
      difficulty_level: 'Medium',
      expansion_packs: true,
      theme: 'Resource Trading',
      components: ['hexagonal tiles', 'resource cards', 'settlements'],
      mechanics: ['Tile Placement', 'Resource Management'],
    },
    {
      id: 2,
      name: 'Ticket to Ride',
      category: 'Family',
      players: '2-5',
      age_range: '8+',
      playing_time: '30-60 minutes',
      difficulty_level: 'Easy',
      expansion_packs: true,
      theme: 'Railroad Building',
      components: ['train cards', 'destination tickets', 'train pieces'],
      mechanics: ['Set Collection', 'Route Building'],
    },
    {
      id: 3,
      name: 'Pandemic',
      category: 'Cooperative',
      players: '2-4',
      age_range: '13+',
      playing_time: '45 minutes',
      difficulty_level: 'Hard',
      expansion_packs: true,
      theme: 'Global Disease Control',
      components: ['city cards', 'disease cubes', 'pandemic board'],
      mechanics: ['Cooperative Play', 'Action Points'],
    },
    {
      id: 4,
      name: 'Codenames',
      category: 'Party',
      players: '4-8+',
      age_range: '14+',
      playing_time: '15 minutes',
      difficulty_level: 'Easy',
      expansion_packs: true,
      theme: 'Word Association',
      components: ['word cards', 'key cards', 'agent cards'],
      mechanics: ['Word Game', 'Team-based'],
    },
    {
      id: 5,
      name: 'Risk',
      category: 'Classic',
      players: '2-6',
      age_range: '10+',
      playing_time: '120 minutes',
      difficulty_level: 'Medium',
      expansion_packs: true,
      theme: 'Global Domination',
      components: ['army pieces', 'territory cards', 'game board'],
      mechanics: ['Area Control', 'Dice Rolling'],
    },
    {
      id: 6,
      name: '7 Wonders',
      category: 'Strategy',
      players: '2-7',
      age_range: '10+',
      playing_time: '30 minutes',
      difficulty_level: 'Medium',
      expansion_packs: true,
      theme: 'Civilization Building',
      components: ['wonder boards', 'resource cards', 'civilization cards'],
      mechanics: ['Drafting', 'Set Collection'],
    },
    {
      id: 7,
      name: 'Carcassonne',
      category: 'Tile-Laying',
      players: '2-5',
      age_range: '7+',
      playing_time: '35 minutes',
      difficulty_level: 'Easy',
      expansion_packs: true,
      theme: 'Medieval Landscape',
      components: ['terrain tiles', 'meeple figures', 'scoreboard'],
      mechanics: ['Tile Placement', 'Area Control'],
    },
    {
      id: 8,
      name: 'Splendor',
      category: 'Engine Building',
      players: '2-4',
      age_range: '10+',
      playing_time: '30 minutes',
      difficulty_level: 'Medium',
      expansion_packs: true,
      theme: 'Renaissance Merchants',
      components: ['gem tokens', 'development cards', 'nobles'],
      mechanics: ['Engine Building', 'Card Drafting'],
    },
    {
      id: 9,
      name: 'Dominion',
      category: 'Deck-Building',
      players: '2-4',
      age_range: '13+',
      playing_time: '30 minutes',
      difficulty_level: 'Medium',
      expansion_packs: true,
      theme: 'Medieval Kingdom',
      components: ['kingdom cards', 'treasure cards', 'victory cards'],
      mechanics: ['Deck-Building', 'Card Drafting'],
    },
    {
      id: 10,
      name: 'The Settlers of Catan',
      category: 'Classic',
      players: '3-4',
      age_range: '10+',
      playing_time: '60-90 minutes',
      difficulty_level: 'Medium',
      expansion_packs: true,
      theme: 'Resource Trading',
      components: ['hexagonal tiles', 'resource cards', 'settlements'],
      mechanics: ['Tile Placement', 'Resource Management'],
    },
    {
      id: 11,
      name: 'Clue',
      category: 'Mystery',
      players: '3-6',
      age_range: '8+',
      playing_time: '45 minutes',
      difficulty_level: 'Easy',
      expansion_packs: false,
      theme: 'Murder Investigation',
      components: ['game board', 'suspect cards', 'weapon tokens'],
      mechanics: ['Deduction', 'Roll and Move'],
    },
    {
      id: 12,
      name: 'Risk Legacy',
      category: 'War',
      players: '3-5',
      age_range: '14+',
      playing_time: '60-120 minutes',
      difficulty_level: 'Hard',
      expansion_packs: false,
      theme: 'World Conquest',
      components: ['board map', 'faction cards', 'permanent stickers'],
      mechanics: ['Legacy Game', 'Area Control'],
    },
    {
      id: 13,
      name: 'Forbidden Island',
      category: 'Cooperative',
      players: '2-4',
      age_range: '10+',
      playing_time: '30 minutes',
      difficulty_level: 'Easy',
      expansion_packs: true,
      theme: 'Adventure',
      components: ['island tiles', 'adventurer cards', 'treasure tokens'],
      mechanics: ['Cooperative Play', 'Tile Placement'],
    },
    {
      id: 14,
      name: 'Munchkin',
      category: 'Card Game',
      players: '3-6',
      age_range: '10+',
      playing_time: '60-90 minutes',
      difficulty_level: 'Easy',
      expansion_packs: true,
      theme: 'Fantasy Parody',
      components: ['door cards', 'treasure cards', 'level tracker'],
      mechanics: ['Take That', 'Role-playing'],
    },
    {
      id: 15,
      name: 'Kingdomino',
      category: 'Family',
      players: '2-4',
      age_range: '8+',
      playing_time: '15-20 minutes',
      difficulty_level: 'Easy',
      expansion_packs: true,
      theme: 'Tile-Laying',
      components: ['domino tiles', 'castle tokens', 'king meeple'],
      mechanics: ['Drafting', 'Tile Placement'],
    },
    {
      id: 16,
      name: 'Azul',
      category: 'Abstract',
      players: '2-4',
      age_range: '8+',
      playing_time: '30-45 minutes',
      difficulty_level: 'Medium',
      expansion_packs: true,
      theme: 'Tile Artistry',
      components: ['pattern boards', 'tiles', 'scoring markers'],
      mechanics: ['Tile Drafting', 'Pattern Building'],
    },
    {
      id: 17,
      name: 'Pictionary',
      category: 'Party',
      players: '4+',
      age_range: '12+',
      playing_time: '60 minutes',
      difficulty_level: 'Easy',
      expansion_packs: false,
      theme: 'Drawing',
      components: ['drawing pads', 'word cards', 'timer'],
      mechanics: ['Drawing', 'Guessing'],
    },
    {
      id: 18,
      name: 'Terraforming Mars',
      category: 'Strategy',
      players: '1-5',
      age_range: '12+',
      playing_time: '120 minutes',
      difficulty_level: 'Hard',
      expansion_packs: true,
      theme: 'Mars Colonization',
      components: ['hex tiles', 'resource cubes', 'corporation cards'],
      mechanics: ['Engine Building', 'Tile Placement'],
    },
    {
      id: 19,
      name: 'Sushi Go!',
      category: 'Card Game',
      players: '2-5',
      age_range: '8+',
      playing_time: '15 minutes',
      difficulty_level: 'Easy',
      expansion_packs: true,
      theme: 'Sushi Collection',
      components: ['sushi cards', 'menu tokens', 'pudding cards'],
      mechanics: ['Drafting', 'Set Collection'],
    },
    {
      id: 20,
      name: 'Gloomhaven',
      category: 'Campaign',
      players: '1-4',
      age_range: '14+',
      playing_time: '60-120 minutes',
      difficulty_level: 'Hard',
      expansion_packs: true,
      theme: 'Fantasy Adventure',
      components: ['scenario book', 'character boards', 'monster standees'],
      mechanics: ['Campaign', 'Cooperative Play'],
    },
    {
      id: 21,
      name: 'Agricola',
      category: 'Worker Placement',
      players: '1-4',
      age_range: '12+',
      playing_time: '30-150 minutes',
      difficulty_level: 'Hard',
      expansion_packs: true,
      theme: 'Farming',
      components: ['family members', 'resource tiles', 'farming boards'],
      mechanics: ['Worker Placement', 'Resource Management'],
    },
    {
      id: 22,
      name: 'Dixit',
      category: 'Party',
      players: '3-6',
      age_range: '8+',
      playing_time: '30 minutes',
      difficulty_level: 'Easy',
      expansion_packs: true,
      theme: 'Storytelling',
      components: ['story cards', 'voting tokens', 'scoreboard'],
      mechanics: ['Bluffing', 'Storytelling'],
    },
  ],
};

const app = express();
const router = jsonServer.router(data);

app.use('/assets', express.static(path.join(__dirname, 'assets')));

app.get('/health', (req, res) => {
  const address = server.address();
  console.log('health check', address);
  res.json({ status: 'UP' });
});

app.use('/api', router);

const server = app.listen(port, host, () => {
  console.log(
    `🎉 products-api up and ready, listening at http://${host}:${port}`
  );
});

server.on('error', console.error);
